apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureBlockHostNamespace
metadata:
  name: psp-host-namespace
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
