# Default values for Azure Policy Add-on on Azure Arc enabled Kubernetes clusters
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Microsoft Azure Policy Add-on on Azure Arc enabled Kubernetes clusters
azurepolicy:
  image:
    name: "mcr.microsoft.com/azure-policy/policy-kubernetes-addon-prod"
    tag: "prod_20201023.1"
## Replace <your_resource_id> with your Azure Arc enabled Kubernetes cluster resource Id. For example: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/testRG/Microsoft.Kubernetes/connectedClusters/testCluster
## Replace <your_client_id> with app Id of the service principal created for Azure Policy Add-on to communicate to Azure Policy service.
## Replace <your_client_secret> with password of the service principal created for Azure Policy Add-on to communicate to Azure Policy service.
## Replace <your_tenant_id> with tenant of the service principal created for Azure Policy Add-on to communicate to Azure Policy service.
  env:
    resourceid: <your_resource_id>
    clientid: <your_client_id>
    clientsecret: <your_client_secret>
    tenantid: <your_tenant_id>
    resourceType: "Microsoft.Kubernetes/connectedClusters"
    policyServiceEndpoint: "https://gov-prod-policy-data.trafficmanager.net"
    fullScanExclusionList: "kube-system,gatekeeper-system,azure-arc"
    webhookExclusionList: "kube-system,gatekeeper-system,azure-arc"

## Microsoft Azure Policy Webhook
azurepolicywebhook:
  image:
    name: "mcr.microsoft.com/azure-policy/policy-kubernetes-webhook"
    tag: "prod_20201023.1"

## OPA Gatekeeper for Kubernetes clusters
gatekeeper:
  image:
    name: "mcr.microsoft.com/oss/open-policy-agent/gatekeeper"
    tag: "v3.1.1"
  resources:
    auditCPULimit: 3000m
    auditMemoryLimit: 1024Mi
    auditCPURequests: 100m
    auditMemoryRequests: 256Mi
    webhookCPULimit: 3000m
    webhookMemoryLimit: 1024Mi
    webhookCPURequests: 100m
    webhookMemoryRequests: 256Mi
    webhookReplicaCount: 2

## Alpine image used in the helm hook
alpine:
  image:
    name: "mcr.microsoft.com/azure-policy/alpine"
    tag: "prod_20200505.1"
